version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errname
    - ginkgolinter
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace
  settings:
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - (^|/)vendor/
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - (^|/)vendor/
