dist: xenial
language: go
go: "1.13"

services:
  - docker
jobs:
  include:
  - stage: Test csv-generator
    name: Test csv-generator
    script: make container-build && ./tests/e2e-test-csv-generator.sh

  - stage: Release
    name: Release to GitHub
    if: tag IS present
    script: |
      docker login -u="${QUAY_BOT}" -p="${QUAY_PASSWORD}" quay.io
      make release IMG_TAG="${TRAVIS_TAG}" VERSION="`echo ${TRAVIS_TAG} | sed 's/^v//'`"
    deploy:
      provider: releases
      name: $TRAVIS_TAG
      api_key: "$GITHUB_TOKEN"
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file: _out/*
      on:
        tags: true
        branch: master
        repo: $TRAVIS_REPO_SLUG

before_script:
  - export PATH=$(pwd):$PATH #with this we can call operator-sdk in makefile
  - make kustomize
  - make operator-sdk
