
namePrefix: "ssp-"

resources:
- manifests.v1beta1.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patches:
- target:
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
  patch: |-
    - op: replace
      path: /webhooks/0/clientConfig/service/name
      value: ssp-webhook-service
    - op: replace
      path: /webhooks/0/clientConfig/service/namespace
      value: kubevirt
