apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: ssp-operator
  name: controller-manager-metrics-service
  namespace: kubevirt
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: ssp-operator
