apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: windows10-installer-run-
  labels:
    pipelinerun: windows10-installer-run
spec:
  params:
  - name: winImageDownloadURL
    value: http://http-server/disk.img
  pipelineRef:
    name: windows-bios-installer
  serviceAccountName: pipeline
status: {}
