apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: windows11-customize-run-
  labels: 
    pipelinerun: windows11-customize-run
spec:
  pipelineRef:
    name: windows-customize
  serviceAccountName: pipeline
status: {}
