apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: windows2k22-customize-run-
  labels: 
    pipelinerun: windows2k22-customize-run
spec:
  params:
    - name: sourceDiskImageName
      value: win2k22
    - name: baseDvName
      value: win2k22-customized
    - name: preferenceName
      value: "windows.2k22"
    - name: customizeConfigMapName
      value: windows-sqlserver
  pipelineRef:
    name: windows-customize
  serviceAccountName: pipeline
status: {}
