---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ssp-operator-allow-ingress-to-ssp-operator-webhook-and-metrics
spec:
  ingress:
  - ports:
    - port: 8443
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          component: kube-apiserver
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-kube-apiserver
      podSelector:
        matchLabels:
          app: openshift-kube-apiserver
    ports:
    - port: 9443
      protocol: TCP
  podSelector:
    matchLabels:
      name: ssp-operator
  policyTypes:
  - Ingress
