# This custom resource is used by upgrade tests

apiVersion: ssp.kubevirt.io/v1beta1
kind: SSP
metadata:
  name: %%_SSP_NAME_%%
  namespace: %%_SSP_NAMESPACE_%%
  labels:
    app.kubernetes.io/part-of: "kubevirt-test"
    app.kubernetes.io/version: "v0.0.0"
spec:
  commonTemplates:
    namespace: %%_COMMON_TEMPLATES_NAMESPACE_%%
  templateValidator:
    replicas: 2
